import mongoose from "mongoose";

const candidateSchema = new mongoose.Schema(
  {
    candidate_code: { type: String, required: true, unique: true },
    cohort_id: { type: mongoose.Schema.Types.ObjectId, ref: "Cohort", required: true, index: true },
    status: {
      type: String,
      enum: ["enrolled", "waitlisted", "rejected", "withdrawn", "graduated"],
      default: "waitlisted",
    },
    waitlist_position: { type: Number, default: null },

    full_name: { type: String, required: true },
    national_id: { type: String, required: true },
    date_of_birth: { type: String, default: null },
    gender: { type: String, default: null },
    phone: { type: String, required: true },
    email: { type: String, default: null },
    district: { type: String, default: null },
    sector: { type: String, default: "" },
    cell: { type: String, default: "" },
    education_level: { type: String, default: "" },
    preferred_language: { type: String, default: "Kinyarwanda" },
    has_smartphone: { type: Boolean, default: false },

    driving_license_number: { type: String, default: null },
    license_categories: { type: String, default: "" },
    license_issue_date: { type: String, default: null },
    years_driving_experience: { type: Number, default: null },
    taxi_association: { type: String, default: "" },
    current_vehicle_plate: { type: String, default: "" },
    currently_driving_for: { type: String, default: "" },
    previously_drove_for_service: { type: Boolean, default: false },

    monthly_income_rwf: { type: Number, default: null },
    average_daily_earnings_rwf: { type: Number, default: null },
    has_bank_account: { type: Boolean, default: false },
    bank_name: { type: String, default: "" },
    bank_account_number: { type: String, default: "" },
    has_existing_loan: { type: Boolean, default: false },
    existing_loan_details: { type: String, default: "" },
    deposit_available_rwf: { type: Number, default: null },
    needs_uza_access_support: { type: Boolean, default: false },
    preferred_term_years: { type: Number, default: null },
    preferred_financing: { type: String, default: null },

    next_of_kin_name: { type: String, default: "" },
    next_of_kin_phone: { type: String, default: "" },
    next_of_kin_relationship: { type: String, default: "" },
    guarantor_name: { type: String, default: "" },
    guarantor_phone: { type: String, default: "" },
    guarantor_occupation: { type: String, default: "" },

    marital_status: { type: String, default: null },
    spouse_name: { type: String, default: "" },
    is_cooperative_member: { type: Boolean, default: false },
    cooperative_name: { type: String, default: "" },
    target_vehicle_price_rwf: { type: Number, default: 0 },
    offers_collateral: { type: Boolean, default: false },
    collateral_description: { type: String, default: "" },
    collateral_value_rwf: { type: Number, default: 0 },
    listed_on_crb: { type: Boolean, default: false },
    crb_resolution_notes: { type: String, default: "" },
    other_loan_bank: { type: String, default: "" },
    other_loan_repayment_source: { type: String, default: "" },

    doc_national_id: { type: Boolean, default: false },
    doc_spouse_id: { type: Boolean, default: false },
    doc_loan_application_letter: { type: Boolean, default: false },
    doc_tax_clearance: { type: Boolean, default: false },
    doc_marital_status_proof: { type: Boolean, default: false },
    doc_proforma_invoice: { type: Boolean, default: false },
    doc_deposit_proof: { type: Boolean, default: false },
    doc_momo_statement: { type: Boolean, default: false },
    doc_yego_history: { type: Boolean, default: false },
    doc_cooperative_letter: { type: Boolean, default: false },
    doc_driving_license: { type: Boolean, default: false },
    doc_previous_vehicle_docs: { type: Boolean, default: false },
    doc_two_passport_photos: { type: Boolean, default: false },
    doc_passport_photo: { type: Boolean, default: false },
    doc_criminal_record: { type: Boolean, default: false },
    doc_proof_of_residence: { type: Boolean, default: false },
    doc_bank_statement: { type: Boolean, default: false },
    doc_medical_certificate: { type: Boolean, default: false },

    training_status: {
      type: String,
      enum: ["not_started", "in_progress", "completed", "failed"],
      default: "not_started",
    },
    attendance_percentage: { type: Number, default: null },
    exam_score: { type: Number, default: null },
    instructor_notes: { type: String, default: null },
    disqualification_reason: { type: String, default: null },

    applied_at: { type: Date, default: Date.now },
  },
  { timestamps: { createdAt: false, updatedAt: "updated_at" } },
);

candidateSchema.index({ cohort_id: 1, national_id: 1 }, { unique: true });

export const Candidate = mongoose.model("Candidate", candidateSchema);
